version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/customer_support
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j  
      - NEO4J_PASSWORD=password
    depends_on:
      - db
      - redis
      - neo4j
    volumes:
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  etl:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/customer_support
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - db
      - redis
      - neo4j
    volumes:
      - ./data:/app/data
    command: python etl_worker/main.py

  mcp:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/customer_support
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - db
      - redis
      - neo4j
    volumes:
      - ./data:/app/data
    command: python app/mcp_server.py

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=customer_support
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
